# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi2', '0003_userwrapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwrapper',
            name='phonenumber',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
