# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi2', '0004_userwrapper_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateField(default=datetime.date(2019, 9, 12)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
