# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi2', '0005_auto_20170519_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwrapper',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userwrapper',
            name='token',
            field=models.CharField(default='', max_length=20),
        ),
    ]
