# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi2', '0006_auto_20170605_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwrapper',
            name='confirm',
            field=models.NullBooleanField(default=False),
        ),
    ]
