# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi2', '0007_auto_20170605_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwrapper',
            name='token',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
